apiVersion: v1
kind: Pod
metadata:
  name: init-pod
  labels:
    app: init-pod   # Added label for Service selector
spec:
  containers:
    - name: myapp
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: db-store

  initContainers:
    - name: webapp
      image: <aws-accountid>.dkr.ecr.us-east-1.amazonaws.com/k8s-init-container:latest
      env:
        - name: AWS_ACCESS_KEY_ID
          value: <access_key_id>
        - name: AWS_SECRET_ACCESS_KEY
          value: <secret_access_key>
        - name: S3_BUCKET_NAME
          value: k8s-init-container-testings
      volumeMounts:
        - mountPath: /data
          name: db-store

  volumes:
    - name: db-store
      emptyDir: {}   # Changed from hostPath to emptyDir

---
apiVersion: v1
kind: Service
metadata:
  name: init-service
spec:
  type: NodePort
  selector:
    app: init-pod   # Match the Pod label
  ports:
    - port: 80          # Service Port
      targetPort: 80    # Container Port
      nodePort: 30080   # External Port
