#apiVersion: v1
#kind: Pod
#metadata:
#  name: s3-test
#  namespace: default
#spec:
#  serviceAccountName: s3-reader
#  containers:
#    - name: aws-cli
#      image: amazon/aws-cli
#      command: ["sh", "-c", "aws s3 ls s3://my-app-bucket"]

apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  serviceAccountName: s3-reader
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  containers:
    - name: myapp
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: db-store
  initContainers:
    - name: webapp
      image: amazon/aws-cli:latest
      command: ["aws", "s3", "cp", "s3://aws-s3-bucket-eks-irsa/", "/aws", "--recursive"]
      volumeMounts:
        - mountPath: /aws
          name: db-store
      imagePullPolicy: Always
      securityContext:
        runAsUser: 0
  volumes:
    - name: db-store
      hostPath:
        path: /aws